### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by dkager**
Kept it quite formal, similar to the German translation.
I wanted to run Touch Mapper locally to confirm it looks OK, but in the end I didn't because it's quite a bit of work. If something is wrong I'll send another patch. :)

A couple of remarks while I'm at it:
- How about "hide buildings" instead of "exclude buildings"? At least in Dutch this sounds a bit more intuitive.
- I struggle a little bit with the phrase "Blind people probably need assistance from a sighted person to do this." It seems easy enough to do with the north-east corner marker. Not to play devil's advocate, but those who can travel independently can probably work out the multipart thing too.

### CODE REVIEW

**Comment by skarkkai** [comment]
Thanks, looks great. I'll merge shortly.

Running Touch Mapper locally isn't as easy as I'd like. But for translating purposes it's fine to leave the code changes to me.

I'm undecided about "hide buildings" vs "exclude buildings", but the former is probably much easier to understand for non-native speakers, so I'll change the wording like that.

The phrase "Blind people probably need assistance from a sighted person to do this." is supposed to refer to making multiple prints that cover a larger area in a sensible way. Sure, it's easy to make multiple prints of adjacent areas, but getting their positions optimal so that they cover everything needed but not unnecessary areas is not, in my own experience. The wording in that phrase could clearly be better.

**Comment by skarkkai** [comment]
The translation is now deployed in https://test.touch-mapper.org/nl/

The only possible issue I can find is the non-translated sentence "Touch Mapper is open source software" in the footer.

**Comment by dkager** [comment]
Kiitos! I will have a look through this tonight.

> The only possible issue I can find is the non-translated sentence "Touch Mapper is open source software" in the footer.

This needed no translation (we borrow all the words from English).

**Comment by skarkkai** [comment]
Interesting that "Touch Mapper is open source software" is the exact same in Dutch. Such an interesting language. I speak some Swedish, and recognize German pretty well, and sometimes it's hard to tell if someone is speaking English, German, Swedish or Dutch :)

**Comment by dkager** [comment]
At the risk of over-generalizing, I would say Dutch borrows the most words from other languages (mostly English in this digital era, but also French and some German). A few friends are helping me to learn Finnish and that certain is very interesting! It's fun to study something other than the Germanic family of languages.

As for the Dutch translation, it looks good. The only thing I noticed is that in the breadcrumbs there's an `aria-current="location"` which can't be translated.

**Comment by skarkkai** [comment]
`aria-current="location"` indicates that the element "represents the current location within an environment or context". So it's not something to be translated.

Hope you have fun with Finnish :)

**Pull request merged**
